### ISSUE TITLE
Discrepancies on mime-types

### ISSUE THREAD

**Issue by nsirolli** [Anomalocaridid/handlr-regex#54]
Isn't the following weird?
```
nico@pilar ~> handlr mime foo.xopp
┌──────────┬────────────────────┐
│ path     │ mime               │
├──────────┼────────────────────┤
│ foo.xopp │ application/x-xopp │
└──────────┴────────────────────┘
nico@pilar ~> file -bL --mime-type foo.xopp
application/gzip
```
Using handlr-regex 0.10.0, on Arch

**Comment by Anomalocaridid** [comment]
That's probably because `file` solely uses the file's contents to determine file type, but `handlr-regex` uses the file extension if there is one and falls back to the file contents otherwise.

This way it's closer to the behavior of the `xdg-*` commands, which solely use the file extension, but still gives a helpful result without a file extension.

**Comment by nsirolli** [comment]
Thanks for your explanation! I'll close this ticket.
