### ISSUE TITLE
0.11.0 can't find any associations when mimeapps.list doesn't exist

### ISSUE THREAD

**Issue by Celti** [Anomalocaridid/handlr-regex#69]
When `~/.config/mimeapps.list` is missing, handlr-regex 0.11.0 returns `no handlers found for <mimetype>` for all invocations of get/open/launch. handlr-regex 0.10.1 has the expected behavior (using a type from the system mimeapps cache).

When a handler is set for a mimetype, the expected behaviour (falling back to the system mimeapps cache) returns. You can reproduce the issue by deleting mimeapps.list or temporarily moving it out of the way. 

I wouldn't have discovered this if this wasn't a brand-new installation without any default handlers set, and it's not exactly a tremendous flaw, but i think it should at least be noted.

**Comment by Anomalocaridid** [comment]
That is certainly a bug and I can replicate it. Fortunately, it seems to already be fixed by the `fix-discussion-68` branch, which I made for problems discussed in #68.

I am still working on fixing the problems mentioned in that discussion, but I already intend to make a new patch release immediately after I finish fixing them and merge the fixes.

Also for now, you may wish to either refrain from using `handlr` to edit `mimeapps.list` or downgrade to v0.10.1, because one of those problems is that if there is no `[Added Associations]` or `[Default Applications]` section, it will more or less **wipe your `mimeapps.list` file** if you try to edit it using `handlr`.
